server:
  port: 8080

spring:
  kafka:
    producer:
      bootstrap-servers: "172.27.164.191:9092"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
    consumer:
      bootstrap-servers: "172.27.164.191:9092"
      group-id: "spring-boot-kafka-consumer"
      key-serializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonDeserializer"

# This is my custom property declared
topic:
  name: "demo1"
