server:
  port: 8080

spring:
  kafka:
    producer:
      bootstrap-servers: "172.17.22.102:9092"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.apache.kafka.common.serialization.StringSerializer"
