server:
  port: 8080

spring:
  kafka:
    producer:
      bootstrap-servers: "172.31.176.132:9092"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
    consumer:
      bootstrap-servers: "172.31.176.132:9092"
      group-id: "spring-boot-kafka-consumer"

# This is my custom property declared
topic:
  name: "demo1"

# netsh interface portproxy add v4tov4 listenport=9092 listenaddress=0.0.0.0 connectport=9092 connectaddress=172.XX.XX.XX