server:
  port: 9081

my:
  vm:
    ip: "172.20.188.82"

spring:
  kafka:
    bootstrap-servers: "${my.vm.ip}:9092"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://${my.vm.ip}:8081"

    consumer:
      group-id: "spring-boot-avro-consumer"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      auto-offset-reset: "earliest"
      properties:
        schema:
          registry:
            url: "http://${my.vm.ip}:8081"
        avro:
          specific:
            reader: "true"


avro:
  topic:
    name: "demo4"

