server:
  port: 9081
spring:
  kafka:
    bootstrap-servers: "172.20.181.222:9092"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://172.20.181.222:8081"

    consumer:
      group-id: "spring-boot-avro-consumer"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      auto-offset-reset: "earliest"
      properties:
        schema:
          registry:
            url: "http://172.20.181.222:8081"
        avro:
          specific:
            reader: "true"


avro:
  topic:
    name: "demo2"

